---
- name: Install web-server and php
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - php
    - php-mysql

- name: Enable and start web-server
  service:
    name: httpd
    state: restarted
    enabled: yes
